const userBookingsData  = [
    {
        shop:'test1',
        location:'alathur',
        phone:'12345678',
        products:['test1','test2','test3'],
        staus:'accepted'
    },
    {
        shop:'test1',
        location:'alathur',
        phone:'12345678',
        products:['test1','test2','test3'],
        staus:'accepted'
    },
    {
        shop:'test1',
        location:'alathur',
        phone:'12345678',
        products:['test1','test2','test3'],
        staus:'rejected'
    },
    {
        shop:'test1',
        location:'alathur',
        phone:'12345678',
        products:['test1','test2','test3'],
        staus:'accepted'
    },
    {
        shop:'test1',
        location:'alathur',
        phone:'12345678',
        products:['test1','test2','test3'],
        staus:'rejected'
    },
    {
        shop:'test1',
        location:'alathur',
        phone:'12345678',
        products:['test1','test2','test3'],
        staus:'accepted'
    },
]

export default userBookingsData