const products_list = [
    {
        product_name:'test',
        price:'1234',
        product_image:'/Images/FindItLogo.png',
        status:'available'
    },
    {
        product_name:'test',
        price:'1234',
        product_image:'/Images/FindItLogo.png',
        status:'available'
    },
    {
        product_name:'test',
        price:'1234',
        product_image:'/Images/FindItLogo.png',
        status:'available'
    },
    {
        product_name:'test',
        price:'1234',
        product_image:'/Images/FindItLogo.png',
        status:'not-available'
    },
    {
        product_name:'test',
        price:'1234',
        product_image:'/Images/FindItLogo.png',
        status:'available'
    },
    {
        product_name:'test',
        price:'1234',
        product_image:'/Images/FindItLogo.png',
        status:'available'
    }
]

export default products_list