const productsData = [
    {
        img:'/Images/profile_icon.png',
        name:'qtest',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Not-Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Not-Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Not-Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Not-Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Not-Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Not-Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'test',
        status:'Available'
    },
    {
        img:'/Images/profile_icon.png',
        name:'rtest',
        status:'Available'
    },
]

export default productsData